CREATE DATABASE TABELA;

USE TABELA;

CREATE TABLE TABELA(
	COLUNA1 VARCHAR(30),
	COLUNA2 VARCHAR(30),
	COLUNA3 VARCHAR(30)
);

ALTER TABLE TABELA
ADD PRIMARY KEY (COLUNA1);

ALTER TABLE TABELA
ADD COLUMN TABELA VARCHAR(30);

ALTER TABLE TABELA
ADD COLUMN TABELA1 VARCHAR(30) NOT NULL UNIQUE
AFTER COLUNA1;

SHOW CREATE TABLE TABELA;